services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=hitstar_backend'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '6543:5432'

  # mqtt server
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
        - "1883:1883"
        - "9001:9001"
    volumes:
      - ./backend/mosquitto:/mosquitto

  # nginx for serving images in backend
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./frontend/main_device/dist:/usr/share/nginx/html/main_device
      - ./nginx_maindevice.conf:/etc/nginx/conf.d/default.conf


  web2:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./frontend/controller/dist:/usr/share/nginx/html/controller
      - ./nginx_controller.conf:/etc/nginx/conf.d/default.conf
      
  web3:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./backend/images:/usr/share/nginx/html/images

