services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

  # mqtt server
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - "./mosquitto:/mosquitto"
