services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=hitstar_backend'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '6543:5432'

  # mqtt server
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
        - "1883:1883"
        - "9001:9001"
    volumes:
      - ../backend/mosquitto:/mosquitto

  # nginx for serving the frontend for the main_device
  web_main_device:
    image: nginx:latest
    container_name: web_main_device
    ports:
      - "8081:80"
    volumes:
      - ../frontend/main_device/dist:/usr/share/nginx/html/main_device
      - ./nginx/main_device/nginx.conf:/etc/nginx/conf.d/default.conf

 # nginx for serving the frontend for the controller
  web_controller:
    image: nginx:latest
    container_name: web_controller
    ports:
      - "8082:80"
    volumes:
      - ../frontend/controller/dist:/usr/share/nginx/html/controller
      - ./nginx/controller/nginx.conf:/etc/nginx/conf.d/default.conf
      
   # nginx for serving the the images and sounds
  web_assets:
    image: nginx:latest
    container_name: web_assets
    ports:
      - "8083:80"
    volumes:
      - ../backend/images:/usr/share/nginx/html/images
      - ../backend/sounds:/usr/share/nginx/html/sounds
      - ./nginx/assets/nginx.conf:/etc/nginx/default.conf

